version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ledger_postgres
    environment:
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_password
      POSTGRES_DB: ledger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ledger_user -d ledger_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ledger_network

volumes:
  postgres_data:
    driver: local

networks:
  ledger_network:
    driver: bridge
